name = "frunk"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[r2_buckets]]
binding = "R2_AVATARS"
bucket_name = "frunk-avatars"
